### ISSUE TITLE
Use Dart generator naming conventions .g.dart

### ISSUE THREAD

**Issue by SuperGNUS** [Parabeac/Parabeac-Core#114]
## Change Proposal
Use the .g.dart output for generated files and only generate .dart files if they don't exist.  This should use darts way
of importing or separating abstract/generated classes.

### Module and Current Solution
Generation modules outputs .dart files which are really generated files.

## Benefits of the Change
Allows the developer to overwrite those .g.dart files without fear of losing changes to .dart files.

**Comment by x64Eddie** [comment]
Hey @GeniusVenture, is this referring to the generated flutter project? modifying the file from `<screen-name>.dart` to `<screen-name>.g.dart` ? Or just having the `build_runner` generate dart files that do not exist 🤔

**Comment by SuperGNUS** [comment]
yes, actually both.  Par beach seems to overwrite main.dart file at times, but in general generating .g.dart and the corresponding .dart implementation file of the .g.dart if it doesn’t exist to include/import the .g.dart file

**Comment by siliconivan** [comment]
I think I understand what you mean now @GeniusVentures, essentially, you want to separate the code that developer might make & the code that is generated so that if you rerun Parabeac-Core on the same project, the only stuff that is overridden is the generated code, hence the .g files. I think this makes a bunch of sense, does that sound about right?

**Comment by SuperGNUS** [comment]
yes, exactly.
