### ISSUE TITLE
Parameter/Override Names aren't filtering through

### ISSUE THREAD

**Issue by SuperGNUS** [Parabeac/Parabeac-Core#127]
As discussed with Eddie a couple of weeks ago, the override names aren't being set in the class, but the
UUID is.

If somebody can fix this soon it should be fairly easy.  Right now the overrides will use UUID like 54334-343-3434334-34334_strvalue for the name which just bloats the code uncessarily.

**Comment by x64Eddie** [comment]
On it! I am going to use generic names for the parameters (var0, var1, etc.) as of right now. From what I remember the overridable value does not come name, just the type and the UUID of the overridable element. Once that is working, ill look into possibly extracting the name of the UI element whose UUID is the same as the overridable parameter and use that as a param name.

**Comment by SuperGNUS** [comment]
Ah, I see from the file.

          "overrideValues": [
            {
              "_class": "overrideValue",
              "overrideName": "4DAF3FC9-389E-44EB-B02B-C9BBDC66EE23_stringValue",
              "value": "Send"
            }

**Comment by SuperGNUS** [comment]
I have an idea for fixing this from the "value" field

**Comment by x64Eddie** [comment]
Yup, for example, in the following overridable property it includes the UUID and type of the parameter. 
![image](https://user-images.githubusercontent.com/29381845/96510040-2f7b6e00-121a-11eb-9f2e-e586bc238be0.png)

If we look at the element that contains the same UUID inside of the symbol master it's going to be a `SketchText` class, a class that represents the actual element of the symbol master if nothing is overridden. The "name" of that class is the current value of the text inside of the symbol, we could use this name as the name of the parameter but is not going to be an accurate name for the parameter ("Information Systems"). Not sure if that is a good alternative? 🤔 
![image](https://user-images.githubusercontent.com/29381845/96510097-4326d480-121a-11eb-8433-8d9ef3ea2d19.png)![image](https://user-images.githubusercontent.com/29381845/96510157-589bfe80-121a-11eb-905c-f03844a495f5.png)


I think the main problem is relaying that information for the symbol instance. Because if we generate optional parameters, then the symbol instance needs to know what name and value its passing. For example, in the card symbol above, the symbol instance would pass 
```
SmallCardSymbol(cardName: "new name")
```
But it needs to know the field `className` in the generation phase, then correlate that to the correct value it's going to pass ("new name"). The other option is to not use optional parameters, which then surfaces another issue. Now the symbol instance has to keep track of the ordering of the parameters, pass the correct value to the correct parameter, and pass null to the ones that are not going to be overridden.

**Comment by x64Eddie** [comment]
> I have an idea for fixing this from the "value" field

@GeniusVentures Is the value going to become the name? 🤔

**Comment by SuperGNUS** [comment]
> > I have an idea for fixing this from the "value" field
> 
> @GeniusVentures Is the value going to become the name? 🤔

Yes.  Are we guaranteed that the Master Symbols will be processed first?
Hmm, might not matter but let me check.

**Comment by x64Eddie** [comment]
No, as of right now. There is no guarantee that master symbols are going to be processed first, unless we force the ordering of the pages on the designer's part. For that, I had created `PBSharedInterAggregationService` which is going to place the symbol instance in a Queue until the symbol master they are referencing is processed. From there the symbol instance can extract the information it needs from the master symbol.

As for the name being the value, how would it work? 🤔 Because if we use the value of a symbol instance as a name, then it has to be communicated to all the symbol instances that reference the master symbol, making sure all use the same parameter name. The name of the parameter needs to come from the master symbol, no? 🤔

**Comment by SuperGNUS** [comment]
Yes, not needed, I figured out how to do this, I should submit the pull request tomorrow.  It does work by just storing the Master Symbols names (with collision detection and override).  Then when you query the name of the parameter, it just looks it up from the global static Map of Symbol ID, UUID of parameter to get the name.

**Comment by SuperGNUS** [comment]
I'm still unclear what the difference between overrides and parameters are, it looks like it just wasn't finished.  I'll add the overrides as optional parameters in the near future.

**Comment by SuperGNUS** [comment]
This will be closed with pull request #129
