### ISSUE TITLE
Change Semantic detection for `.*` to `<>`

### ISSUE THREAD

**Issue by siliconivan** [Parabeac/Parabeac-Core#17]
This has been discussed with the Parabeac team, but this would be a more natural approach to applying a naming semantic. It doesn't make or break anything but would be a better UX on the Sketch side.

**Comment by DepressoExpressoBoi** [comment]
Hey @x64Eddie, I heard you had ideas for making this change and wanted to help out. So whenever you have the chance so we can discuss how to actually make this change and get it done.

**Comment by x64Eddie** [comment]
Hey @DepressoExpressoBoi! Sorry for the late response! Yeah, for this issue is enforcing a standard of declaring semantics, using `<>` within the semantic name. For example, `"<login-button>"` could be a _semantic_ of a login button. However, technically there is no standard in how you right semantics for eggs inside of Parabeac-Core. You could have `"!login-button!"`, `"*login-button"`, `"<login-button>"` or even just `"login-button"` for that particular egg. This is the case because in the service that handles eggs and semantics Parabeac-Core is checking if the name contains the semantic `(name.contains(semantic))`. Instead of that, you would need to make sure Parabeac-Core ignores everything that does not follow the correct standard. In the example mentioned, Parabeac-Core would ignore everything except `"<login-button>"`. To make that work, you are going to have to replace the _contains_ by something else. You could tokenize the string and see if the string inside `<>` matches the semantic of the egg.

**Comment by siliconivan** [comment]
Hey @DepressoExpressoBoi, just wanted to see if you still wanted to take on this issue. Completely understand if you're busy, I might take on this issue.

**Comment by DepressoExpressoBoi** [comment]
Hey @siliconivan, I was interested in taking this issue, but I am a little swamped with work at the moment. So I am completely cool with you taking it on. I can see what I can help with later on when I am not as swamped.

**Comment by siliconivan** [comment]
Sweet, thanks man!
