### ISSUE TITLE
Should Parabeac-core be able to generate output even though, flutter pub get, cannot get packages?

### ISSUE THREAD

**Issue by SushiRoll53** [Parabeac/Parabeac-Core#335]
This has happens once, since it is not common that `flutter pub get` does not work, but I think it should be something that shouldn't stop PBC from working properly

![Screen_Shot_2021-03-24_at_9 55 53_PM](https://user-images.githubusercontent.com/35854816/112527541-ca97e700-8d68-11eb-89ec-d9832979b8ba.png)

Basically, what happened was that PBC got stuck waiting on `flutter pub get`

**Comment by ivan-015** [comment]
I think this is somewhat tricky since parabeac-core depends on many packages to work properly (see pubspec.yaml). Therefore I believe if pub goes down again, the only way parabeac-core will work is if the user ran `pub get` before the site went down. Feel free to let me know if you know a way to circumvent this 🤔
