### ISSUE TITLE
SketchAssetConverter migrate web server to executable CLI

### ISSUE THREAD

**Issue by ChangJoo-Park** [Parabeac/Parabeac-Core#38]
## Change Proposal

I think using SketchAssetConverter as a web server is an awesome solution, but It has a little problem. When Parabeac users already running a webserver on a their local machine, Parabeac is not working. furthermore, I did not meet the error with the converter server has done. Next time I could not be using Parabeac. it because using a web server way.

## Benefits of the Change

I suggest SketchAssetConverter as an executable. It can be a solution from already running webserver PORT. CLI way can detach the converter from Parabeac-Core. It is made easier to maintain. When Parabeac running on the cloud, maybe it is future :), Every single time users request sketch to flutter, It will be a single point of failure

**Comment by x64Eddie** [comment]
Yeah, you have a point of running SketchAssetConverter(SAC) as CLI locally, good call👍🏼 . It was left as a web server due to time constraints. 
However, not sure if you agree or disagree with running SAC as a web server in the cloud but ill share my _opinion_ on why it should, we can then discuss the pros and cons!🤘 When Parabeac does run in the cloud, SAC would run as a web server, we don't want to couple Parabeac Core to SAC. There are two reasons for this. First, SAC requires an OSX environment to run. This is the case because it makes use of the Sketchtool. If SAC was coupled to Parabeac Core, it would inherently force Parabeac Core to run in an OSX environment as well. The final reason is that SAC is going to be doing more than just converting SketchVectors to Image, a set of responsibilities than don't align with Parabeac Core's responsibilities. 🤔

**Comment by ChangJoo-Park** [comment]
Thanks for reply @x64Eddie  :) I understand your thought. The limitation is "SAC requires an OSX". SAC is using a web server has no problem at this time. I focus on generating code better.  When need to change the webserver to CLI, I dive in this issue

**Comment by siliconivan** [comment]
Closing this issue out since Windows cannot run Sketch Tool.
