### ISSUE TITLE
Add Batch File Versions of the Shell Scripts within Parabeac Core

### ISSUE THREAD

**Issue by Ihuds577** [Parabeac/Parabeac-Core#57]
## Description
This is a base functionality needed to enable Windows Support for Parabeac Core as shell scripts do not run on Windows. By rewriting the shell scripts in their bash equivalent and then adding in the ability to run those scripts based on the OS that Parabeac Core is in this should allow for Parabeac Core to run on Windows.

## Files Affected:
* all .sh files

## Additional Notes:

**Comment by ivan-015** [comment]
One thing to note about this Issue is that it is likely that detecting what OS the user is running is necessary to run the correct scripts. In addition, it is possible that the optional value `runInShell` of `Process.runSync()` will have to be adjusted to properly work with Windows.

**Comment by avats-dev** [comment]
@Ihuds577 @ivan-015 can you elaborate more on how to implement this? I want to contribute, thanks.

**Comment by ivan-015** [comment]
Hey @avats-dev ! Sure thing, if you look at the directory `pb-scripts` we only have .sh files, which means that they cannot be executed through Windows systems. We'd like to have batch equivalent of the .sh scripts so that they can be run easily from windows. In addition, as seen in the comment above, some changes may need to happen inside the codebase which detects what OS the user is running to detect which scripts should be run in addition to making sure that the `Process.run()` calls can properly run these batch commands. Hopefully this helped!
