### ISSUE TITLE
Parabeac trashes main.dart on exception

### ISSUE THREAD

**Issue by SuperGNUS** [Parabeac/Parabeac-Core#97]
If you create a group inside Sketch with no children, Parabeac will except out and your main.dart file will become blank.

You can regenerate it, but you lose any changes you have added.

**Comment by siliconivan** [comment]
Hmm, that's annoying. I'll take a look.

**Comment by SuperGNUS** [comment]
To duplicate, group some objects together in sketch and then move those objects up to the artboard which leaves the group.

Run parabeac on that sketch file and lib/main.dart is blanked out.

**Comment by siliconivan** [comment]
Update on this issue, it may be related to misc. items in general.

**Comment by siliconivan** [comment]
The issue here is resulting from the fact that we don't save the property name on all nodes. This becomes a problem when processing a miscellaneous node, which is essentially a node that is not placed inside of an Artboard or Symbol. This could easily be fixed for some cases by enforcing all 'inherited' nodes to set the name value. (Inherited just means it was a direct interpretation from design to intermediate, that nothing special happened to generate that node). However, the problem would appear again if a misc. item was then interpreted as an egg. So it seems like every node needs to have a name otherwise this error will continue to show up. It sucks that in most cases, this property is not needed whatsoever. Thoughts?

**Comment by siliconivan** [comment]
This issue should've been closed with a PR to dev
